/**
 * sheetDefs.ts - AG Grid column definitions for all 30 LIMS Load Sheet tabs.
 */

import { SheetDef } from '../../types/lims';

export const SHEET_DEFS: SheetDef[] = [
  {
    dataKey: 'analysis_types',
    name: 'ANALYSIS_TYPES',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'description', headerName: 'DESCRIPTION', width: 250 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
    ],
  },
  {
    dataKey: 'common_names',
    name: 'COMMON_NAME',
    columns: [
      { field: 'name', headerName: 'NAME', width: 150 },
      { field: 'description', headerName: 'DESCRIPTION', width: 300 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
    ],
  },
  {
    dataKey: 'analysis',
    name: 'ANALYSIS',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'version', headerName: 'VERSION', width: 90 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
      { field: 'active', headerName: 'ACTIVE', width: 80 },
      { field: 'reported_name', headerName: 'REPORTED_NAME', width: 200 },
      { field: 'common_name', headerName: 'COMMON_NAME', width: 150 },
      { field: 'analysis_type', headerName: 'ANALYSIS_TYPE', width: 150 },
      { field: 'description', headerName: 'DESCRIPTION', width: 250 },
    ],
  },
  {
    dataKey: 'components',
    name: 'COMPONENT',
    columns: [
      { field: 'analysis', headerName: 'ANALYSIS', width: 180 },
      { field: 'name', headerName: 'NAME', width: 200 },
      { field: 'num_replicates', headerName: 'NUM_REPLICATES', width: 130 },
      { field: 'version', headerName: 'VERSION', width: 90 },
      { field: 'order_number', headerName: 'ORDER_NUMBER', width: 120 },
      { field: 'result_type', headerName: 'RESULT_TYPE', width: 120 },
      { field: 'units', headerName: 'UNITS', width: 100 },
      { field: 'minimum', headerName: 'MINIMUM', width: 100 },
      { field: 'maximum', headerName: 'MAXIMUM', width: 100 },
    ],
  },
  {
    dataKey: 'units',
    name: 'UNITS',
    columns: [
      { field: 'unit_code', headerName: 'UNIT_CODE', width: 120 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'display_string', headerName: 'DISPLAY_STRING', width: 120 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
    ],
  },
  {
    dataKey: 'products',
    name: 'PRODUCT',
    columns: [
      { field: 'product', headerName: 'PRODUCT', width: 200 },
      { field: 'version', headerName: 'VERSION', width: 90 },
      { field: 'sampling_point', headerName: 'SAMPLING_POINT', width: 150 },
      { field: 'grade', headerName: 'GRADE', width: 120 },
      { field: 'order_number', headerName: 'ORDER_NUMBER', width: 120 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'continue_checking', headerName: 'CONTINUE_CHECKING', width: 150 },
      { field: 'test_list', headerName: 'TEST_LIST', width: 150 },
      { field: 'always_check', headerName: 'ALWAYS_CHECK', width: 130 },
      { field: 't_ph_same_lot', headerName: 'T_PH_SAME_LOT', width: 130 },
      { field: 't_ph_status1', headerName: 'T_PH_STATUS1', width: 120 },
      { field: 't_ph_status2', headerName: 'T_PH_STATUS2', width: 120 },
      { field: 't_ph_recert', headerName: 'T_PH_RECERT', width: 120 },
      { field: 't_usp_secondary', headerName: 'T_USP_SECONDARY', width: 140 },
      { field: 'test_location', headerName: 'TEST_LOCATION', width: 130 },
      { field: 'reqd_volume', headerName: 'REQD_VOLUME', width: 120 },
      { field: 'aliquot_group', headerName: 'ALIQUOT_GROUP', width: 130 },
      { field: 'c_spec_variation', headerName: 'C_SPEC_VARIATION', width: 140 },
      { field: 'c_test_group', headerName: 'C_TEST_GROUP', width: 130 },
    ],
  },
  {
    dataKey: 'tph_grades',
    name: 'T_PH_GRADE',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'description', headerName: 'DESCRIPTION', width: 250 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
      { field: 'active', headerName: 'ACTIVE', width: 80 },
      { field: 'code', headerName: 'CODE', width: 100 },
    ],
  },
  {
    dataKey: 'sampling_points',
    name: 'SAMPLING_POINT',
    columns: [
      { field: 'name', headerName: 'NAME', width: 200 },
      { field: 'description', headerName: 'DESCRIPTION', width: 300 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
    ],
  },
  {
    dataKey: 'product_grades',
    name: 'PRODUCT_GRADE',
    columns: [
      { field: 'product', headerName: 'PRODUCT', width: 200 },
      { field: 'version', headerName: 'VERSION', width: 90 },
      { field: 'grade', headerName: 'GRADE', width: 120 },
      { field: 'order_number', headerName: 'ORDER_NUMBER', width: 120 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'continue_checking', headerName: 'CONTINUE_CHECKING', width: 150 },
      { field: 'test_list', headerName: 'TEST_LIST', width: 150 },
      { field: 'always_check', headerName: 'ALWAYS_CHECK', width: 130 },
    ],
  },
  {
    dataKey: 'prod_grade_stages',
    name: 'PROD_GRADE_STAGE',
    columns: [
      { field: 'product', headerName: 'PRODUCT', width: 180 },
      { field: 'version', headerName: 'VERSION', width: 90 },
      { field: 'sampling_point', headerName: 'SAMPLING_POINT', width: 140 },
      { field: 'grade', headerName: 'GRADE', width: 120 },
      { field: 'stage', headerName: 'STAGE', width: 120 },
      { field: 'analysis', headerName: 'ANALYSIS', width: 180 },
      { field: 'order_number', headerName: 'ORDER_NUMBER', width: 120 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'spec_type', headerName: 'SPEC_TYPE', width: 110 },
      { field: 'num_reps', headerName: 'NUM_REPS', width: 100 },
      { field: 'partial', headerName: 'PARTIAL', width: 90 },
      { field: 'ext_link', headerName: 'EXT_LINK', width: 100 },
      { field: 'reported_name', headerName: 'REPORTED_NAME', width: 180 },
      { field: 'variation', headerName: 'VARIATION', width: 110 },
      { field: 'required', headerName: 'REQUIRED', width: 100 },
    ],
  },
  {
    dataKey: 'product_specs',
    name: 'PRODUCT_SPEC',
    columns: [
      { field: 'product', headerName: 'PRODUCT', width: 180 },
      { field: 'version', headerName: 'VERSION', width: 90 },
      { field: 'sampling_point', headerName: 'SAMPLING_POINT', width: 140 },
      { field: 'grade', headerName: 'GRADE', width: 100 },
      { field: 'stage', headerName: 'STAGE', width: 120 },
      { field: 'analysis', headerName: 'ANALYSIS', width: 180 },
      { field: 'component', headerName: 'COMPONENT', width: 180 },
      { field: 'units', headerName: 'UNITS', width: 100 },
      { field: 'round', headerName: 'ROUND', width: 80 },
      { field: 'rule_type', headerName: 'RULE_TYPE', width: 110 },
      { field: 'spec_rule', headerName: 'SPEC_RULE', width: 120 },
      { field: 'min_value', headerName: 'MIN_VALUE', width: 100 },
      { field: 'max_value', headerName: 'MAX_VALUE', width: 100 },
      { field: 'text_value', headerName: 'TEXT_VALUE', width: 130 },
      { field: 'class_', headerName: 'CLASS', width: 90 },
      { field: 'required', headerName: 'REQUIRED', width: 100 },
    ],
  },
  {
    dataKey: 'tph_item_codes',
    name: 'T_PH_ITEM_CODE',
    columns: [
      { field: 't_ph_item_code', headerName: 'T_PH_ITEM_CODE', width: 180 },
      { field: 'supplier', headerName: 'SUPPLIER', width: 150 },
      { field: 'active', headerName: 'ACTIVE', width: 80 },
      { field: 'status1', headerName: 'STATUS1', width: 100 },
      { field: 'status2', headerName: 'STATUS2', width: 100 },
      { field: 'order_number', headerName: 'ORDER_NUMBER', width: 120 },
      { field: 'retest_interval', headerName: 'RETEST_INTERVAL', width: 130 },
      { field: 'expiry_interval', headerName: 'EXPIRY_INTERVAL', width: 130 },
      { field: 'full_test_freq', headerName: 'FULL_TEST_FREQ', width: 130 },
      { field: 'lots_to_go', headerName: 'LOTS_TO_GO', width: 110 },
      { field: 'date_last_tested', headerName: 'DATE_LAST_TESTED', width: 150 },
    ],
  },
  {
    dataKey: 'tph_item_code_specs',
    name: 'T_PH_ITEM_CODE_SPEC',
    columns: [
      { field: 'spec_code', headerName: 'SPEC_CODE', width: 150 },
      { field: 't_ph_item_code', headerName: 'T_PH_ITEM_CODE', width: 180 },
      { field: 'product_spec', headerName: 'PRODUCT_SPEC', width: 150 },
      { field: 'spec_class', headerName: 'SPEC_CLASS', width: 120 },
      { field: 'order_number', headerName: 'ORDER_NUMBER', width: 120 },
      { field: 'grade', headerName: 'GRADE', width: 100 },
      { field: 'common_grade', headerName: 'COMMON_GRADE', width: 130 },
    ],
  },
  {
    dataKey: 'tph_item_code_supps',
    name: 'T_PH_ITEM_CODE_SUPP',
    columns: [
      { field: 't_ph_item_code', headerName: 'T_PH_ITEM_CODE', width: 180 },
      { field: 'supplier', headerName: 'SUPPLIER', width: 150 },
      { field: 'active', headerName: 'ACTIVE', width: 80 },
      { field: 'status1', headerName: 'STATUS1', width: 100 },
      { field: 'status2', headerName: 'STATUS2', width: 100 },
      { field: 'order_number', headerName: 'ORDER_NUMBER', width: 120 },
    ],
  },
  {
    dataKey: 'tph_sample_plans',
    name: 'T_PH_SAMPLE_PLAN',
    columns: [
      { field: 'name', headerName: 'NAME', width: 200 },
      { field: 'version', headerName: 'VERSION', width: 90 },
      { field: 'active', headerName: 'ACTIVE', width: 80 },
      { field: 'description', headerName: 'DESCRIPTION', width: 300 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
    ],
  },
  {
    dataKey: 'tph_sample_plan_entries',
    name: 'T_PH_SAMPLE_PLAN_EN',
    columns: [
      { field: 't_ph_sample_plan', headerName: 'T_PH_SAMPLE_PLAN', width: 180 },
      { field: 'entry_code', headerName: 'ENTRY_CODE', width: 120 },
      { field: 'version', headerName: 'VERSION', width: 90 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'order_number', headerName: 'ORDER_NUMBER', width: 120 },
      { field: 'spec_type', headerName: 'SPEC_TYPE', width: 110 },
      { field: 'spec_status', headerName: 'SPEC_STATUS', width: 110 },
      { field: 't_ph_sample_type', headerName: 'T_PH_SAMPLE_TYPE', width: 150 },
      { field: 'log_sample', headerName: 'LOG_SAMPLE', width: 110 },
      { field: 'create_inventory', headerName: 'CREATE_INVENTORY', width: 140 },
      { field: 'retained_sample', headerName: 'RETAINED_SAMPLE', width: 140 },
      { field: 'stability', headerName: 'STABILITY', width: 100 },
      { field: 'initial_status', headerName: 'INITIAL_STATUS', width: 130 },
      { field: 'indic_samples', headerName: 'INDIC_SAMPLES', width: 120 },
      { field: 'quantity', headerName: 'QUANTITY', width: 100 },
      { field: 'units', headerName: 'UNITS', width: 90 },
      { field: 'c_reanalysis_qty', headerName: 'C_REANALYSIS_QTY', width: 140 },
      { field: 'c_stm_quantity', headerName: 'C_STM_QUANTITY', width: 130 },
    ],
  },
  {
    dataKey: 'customers',
    name: 'CUSTOMER',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'company_name', headerName: 'COMPANY_NAME', width: 200 },
      { field: 'address1', headerName: 'ADDRESS1', width: 200 },
      { field: 'address2', headerName: 'ADDRESS2', width: 200 },
      { field: 'address3', headerName: 'ADDRESS3', width: 150 },
      { field: 'address4', headerName: 'ADDRESS4', width: 150 },
      { field: 'address5', headerName: 'ADDRESS5', width: 150 },
      { field: 'address6', headerName: 'ADDRESS6', width: 150 },
      { field: 'fax_num', headerName: 'FAX_NUM', width: 130 },
      { field: 'phone_num', headerName: 'PHONE_NUM', width: 130 },
      { field: 'contact', headerName: 'CONTACT', width: 150 },
      { field: 'email_addr', headerName: 'EMAIL_ADDR', width: 200 },
    ],
  },
  {
    dataKey: 't_sites',
    name: 'T_SITE',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'description', headerName: 'DESCRIPTION', width: 250 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
      { field: 'parent_site', headerName: 'PARENT_SITE', width: 150 },
    ],
  },
  {
    dataKey: 't_plants',
    name: 'T_PLANT',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'description', headerName: 'DESCRIPTION', width: 250 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
      { field: 'site', headerName: 'SITE', width: 150 },
      { field: 'personnel_smp_type', headerName: 'PERSONNEL_SMP_TYPE', width: 160 },
      { field: 'personnel_stage', headerName: 'PERSONNEL_STAGE', width: 150 },
      { field: 'personnel_spec_type', headerName: 'PERSONNEL_SPEC_TYPE', width: 170 },
    ],
  },
  {
    dataKey: 't_suites',
    name: 'T_SUITE',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'description', headerName: 'DESCRIPTION', width: 250 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
      { field: 'plant', headerName: 'PLANT', width: 150 },
      { field: 'visual_workflow', headerName: 'VISUAL_WORKFLOW', width: 140 },
      { field: 'corrective_action', headerName: 'CORRECTIVE_ACTION', width: 160 },
      { field: 'restrict_collection', headerName: 'RESTRICT_COLLECTION', width: 160 },
    ],
  },
  {
    dataKey: 'process_units',
    name: 'PROCESS_UNIT',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
      { field: 'product_grade', headerName: 'PRODUCT_GRADE', width: 140 },
      { field: 'sample_template', headerName: 'SAMPLE_TEMPLATE', width: 150 },
      { field: 'running', headerName: 'RUNNING', width: 100 },
      { field: 'phase', headerName: 'PHASE', width: 100 },
      { field: 'default_phase', headerName: 'DEFAULT_PHASE', width: 130 },
      { field: 't_alternate_grade', headerName: 'T_ALTERNATE_GRADE', width: 150 },
      { field: 't_corrective_action', headerName: 'T_CORRECTIVE_ACTION', width: 170 },
      { field: 't_suite', headerName: 'T_SUITE', width: 120 },
    ],
  },
  {
    dataKey: 'proc_sched_parents',
    name: 'PROC_SCHED_PARENT',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'first_day_of_week', headerName: 'FIRST_DAY_OF_WEEK', width: 150 },
      { field: 'treat_holidays_as', headerName: 'TREAT_HOLIDAYS_AS', width: 150 },
      { field: 'workstation', headerName: 'WORKSTATION', width: 130 },
      { field: 'running', headerName: 'RUNNING', width: 100 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
      { field: 'active_flag', headerName: 'ACTIVE_FLAG', width: 110 },
      { field: 'version', headerName: 'VERSION', width: 90 },
      { field: 't_site', headerName: 'T_SITE', width: 120 },
    ],
  },
  {
    dataKey: 'process_schedules',
    name: 'PROCESS_SCHEDULE',
    columns: [
      { field: 'schedule_number', headerName: 'SCHEDULE_NUMBER', width: 150 },
      { field: 'unit', headerName: 'UNIT', width: 120 },
      { field: 'sampling_point', headerName: 'SAMPLING_POINT', width: 140 },
      { field: 'test_list', headerName: 'TEST_LIST', width: 130 },
      { field: 'analyses', headerName: 'ANALYSES', width: 150 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'schedule_name', headerName: 'SCHEDULE_NAME', width: 150 },
      { field: 'order_number', headerName: 'ORDER_NUMBER', width: 120 },
      { field: 'running', headerName: 'RUNNING', width: 100 },
      { field: 'version', headerName: 'VERSION', width: 90 },
      { field: 'spec_type', headerName: 'SPEC_TYPE', width: 110 },
      { field: 'stage', headerName: 'STAGE', width: 100 },
    ],
  },
  {
    dataKey: 'lists',
    name: 'LIST',
    columns: [
      { field: 'list_name', headerName: 'LIST', width: 150 },
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'value', headerName: 'VALUE', width: 150 },
      { field: 'order_number', headerName: 'ORDER_NUMBER', width: 120 },
    ],
  },
  {
    dataKey: 'list_entries',
    name: 'LIST_ENTRY',
    columns: [
      { field: 'name', headerName: 'NAME', width: 200 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
      { field: 'description', headerName: 'DESCRIPTION', width: 300 },
    ],
  },
  {
    dataKey: 'vendors',
    name: 'VENDOR',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'contact', headerName: 'CONTACT', width: 150 },
      { field: 'company_name', headerName: 'COMPANY_NAME', width: 200 },
      { field: 'phone_num', headerName: 'PHONE_NUM', width: 130 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
    ],
  },
  {
    dataKey: 'suppliers',
    name: 'SUPPLIER',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'contact', headerName: 'CONTACT', width: 150 },
      { field: 'company_name', headerName: 'COMPANY_NAME', width: 200 },
      { field: 'phone_num', headerName: 'PHONE_NUM', width: 130 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
    ],
  },
  {
    dataKey: 'instruments',
    name: 'INSTRUMENTS',
    columns: [
      { field: 'name', headerName: 'NAME', width: 180 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'inst_group', headerName: 'INST_GROUP', width: 130 },
      { field: 'vendor', headerName: 'VENDOR', width: 150 },
      { field: 'on_line', headerName: 'ON_LINE', width: 90 },
      { field: 'serial_no', headerName: 'SERIAL_NO', width: 130 },
      { field: 'pm_date', headerName: 'PM_DATE', width: 110 },
      { field: 'pm_intv', headerName: 'PM_INTV', width: 90 },
      { field: 'calib_date', headerName: 'CALIB_DATE', width: 110 },
      { field: 'calib_intv', headerName: 'CALIB_INTV', width: 100 },
      { field: 'model_no', headerName: 'MODEL_NO', width: 130 },
    ],
  },
  {
    dataKey: 'lims_users',
    name: 'LIMS_USERS',
    columns: [
      { field: 'user_name', headerName: 'USER_NAME', width: 150 },
      { field: 'full_name', headerName: 'FULL_NAME', width: 200 },
      { field: 'phone', headerName: 'PHONE', width: 130 },
      { field: 'group_name', headerName: 'GROUP_NAME', width: 150 },
      { field: 'description', headerName: 'DESCRIPTION', width: 200 },
      { field: 'email_addr', headerName: 'EMAIL_ADDR', width: 200 },
      { field: 'is_role', headerName: 'IS_ROLE', width: 90 },
      { field: 'uses_roles', headerName: 'USES_ROLES', width: 120 },
      { field: 'language_prefix', headerName: 'LANGUAGE_PREFIX', width: 140 },
      { field: 't_site', headerName: 'T_SITE', width: 120 },
      { field: 'location_lab', headerName: 'LOCATION_LAB', width: 130 },
    ],
  },
  {
    dataKey: 'versions',
    name: 'VERSIONS',
    columns: [
      { field: 'table_name', headerName: 'TABLE_NAME', width: 200 },
      { field: 'version', headerName: 'VERSION', width: 100 },
      { field: 'description', headerName: 'DESCRIPTION', width: 300 },
    ],
  },
];
